### ISSUE TITLE
Scrape from Wikidata and Wikipedia

### ISSUE THREAD

**Issue by katyhuff** [arfc/webscraping#4]
Hi @ytan15 ! Sorry it took a while to describe this goal. Let's see what you can get into your sqlite3 file out of wikipedia alone. Here are some tutorials on scraping wikipedia and wikidata:

- http://www.thehackerwithin.org/berkeley/posts/wikiscraping-spring-2016
- https://github.com/thehackerwithin/berkeley/tree/master/code_examples/scraping_wikipedia

You ought to be able to find names and locations of reactors. You may also be able to find some of the other columns as well. Let us know what you can find!

**Comment by ytan15** [comment]
@katyhuff No problem! I'm working on it!

**Comment by katyhuff** [comment]
I think this is closed by #5 and #9 .
