### ISSUE TITLE
Scrape from the PRIS database

### ISSUE THREAD

**Issue by katyhuff** [arfc/webscraping#8]
Next step, if you're getting frustrated with wikipedia: check out the [PRIS database](https://www.iaea.org/pris/). If necessary, @jbae11 can help with understanding it and perhaps would be willing to show you what he's done so far.

Some, but not all, of the information we want, should be in that database.

**Comment by jbae11** [comment]
If you need any help or have any questions in regards to the PRIS data do not hesitate to 'slack' me or just visit the office! 

also in our [fuel cycle box](https://uofi.app.box.com/files/0/f/19914589406/fuel-cycle), 
I have uploaded the csv file for anyone to use! You just need to cite PRIS when using it for a publication or something

**Comment by jbae11** [comment]
Can I close this issue @ytan15 ?
